# Generated by Django 6.0.6 on 2026-07-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts_per_email',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='participant_email',
            field=models.EmailField(max_length=254),
        ),
    ]
